cmake -G "NMake Makefiles" ^
 -DCMAKE_CXX_FLAGS="/MT /GS-" ^
 -DCMAKE_CXX_FLAGS_DEBUG="/Zi /DDEBUG" ^
 -DCMAKE_CXX_FLAGS_RELEASE="/O2 /DNDEBUG" ^
 -DCMAKE_EXE_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_MODULE_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_STATIC_LINKER_FLAGS="/machine:amd64" ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_INSTALL_PREFIX=E:\usr ^
 ..

